#!/usr/bin/env python
# -*- coding: utf-8 -*-

# ------------------------------------------------------------
# 多语言测试需求国家列表更新时间：20241014
# ------------------------------------------------------------

class Language:

    notes = """
    词条测试需求国家列表更新时间为：20250401
    https://odocs.myoas.com/sheets/16q8MwozVrt2gKk7/QXVc3
    请在多语言测试需求国家更新后及时更新
    """

    d = ["阿拉伯语（阿拉伯）=ar-AR",
         "藏语（中国）=bo-CN",
         "俄语=ru-RU",
         "法语=fr-FR",
         "菲律宾语=fil-PH",
         "高棉语=km-KH",
         "韩语=ko-KR",
         "老挝语=lo-LA",
         "马来语=ms-MY",
         "孟加拉语=bn-BD",
         "缅甸语(MM)=My-MM",
         "尼泊尔语=ne-NP",
         "日语=ja-JP",
         "泰语=th-TH",
         "维吾尔语（中国）=ug-CN",
         "印地语=hi-IN",
         "印尼语=id-ID",
         "英语（美国）=en-US",
         "越南语=vi-VN",
         "中文（台湾）=zh-TW",
         "中文（香港）=zh-HK",
         "中文（中国）=zh-CN",
         "数字语言=kea-CV", ]
    de = ["阿拉伯语（阿拉伯）=ar-AR",
          "阿萨姆语=as-IN",
          "奥里亚语=or-IN",
          "巴斯克语=eu-ES",
          "保加利亚语=bg-BG",
          "波兰语=pl-PL",
          "波斯语=fa-IR",
          "藏语（中国）=bo-CN",
          "丹麦语=da-DK",
          "德语=de-DE",
          "德语(瑞士)=de-CH",
          "俄语=ru-RU",
          "法语=fr-FR",
          "菲律宾语=fil-PH",
          "芬兰语=fi-FI",
          "高棉语=km-KH",
          "古吉拉特语=gu-IN",
          "哈萨克语=kk-KZ",
          "韩语=ko-KR",
          "荷兰语=nl-NL",
          "加利西亚语=gl-ES",
          "加泰罗尼亚语=ca-ES",
          "捷克语=cs-CZ",
          "卡纳达语=kn-IN",
          "克罗地亚语=hr-HR",
          "老挝语=lo-LA",
          "罗马尼亚语=ro-RO",
          "马拉地语=mr-IN",
          "马拉雅拉姆语=ml-IN",
          "马来语=ms-MY",
          "孟加拉语=bn-BD",
          "缅甸语(MM)=My-MM",
          "尼泊尔语=ne-NP",
          "挪威语=nb-NO",
          "旁遮普语=pa-IN",
          "葡萄牙语(巴西)=pt-BR",
          "葡萄牙语(葡萄牙)=pt-PT",
          "日语=ja-JP",
          "瑞典语=sv-SE",
          "塞尔维亚语=sr-RS",
          "僧伽罗语=si-LK",
          "斯洛伐克语=sk-SK",
          "斯洛文尼亚语=sl-SI",
          "斯瓦西里语=sw-KE",
          "泰卢固语=te-IN",
          "泰米尔语=ta-IN",
          "泰语=th-TH",
          "土耳其语=tr-TR",
          "维吾尔语（中国）=ug-CN",
          "乌尔都语（巴基斯坦）=ur-PK",
          "乌克兰语=uk-UA",
          "乌兹别克语=uz-UZ",
          "西班牙语(墨西哥)=es-MX",
          "西班牙语(西班牙)=es-ES",
          "希伯来语（以色列）=iw-IL",
          "希腊语=el-GR",
          "匈牙利语=hu-HU",
          "意大利语=it-IT",
          "印地语=hi-IN",
          "印尼语=id-ID",
          "英文（澳大利亚）=en-AU",
          "英文（新西兰）=en-NZ",
          "英语（美国）=en-US",
          "英语（英国）=en-GB",
          "越南语=vi-VN",
          "中文（台湾）=zh-TW",
          "中文（香港）=zh-HK",
          "中文（中国）=zh-CN",
          "数字语言=kea-CV",
          "阿塞拜疆语（阿塞拜疆）=az-AZ",
          "格鲁吉亚语（格鲁吉亚）=ka-GE",
          "亚美尼亚语（亚美尼亚）=hy-AM",
          "波斯尼亚语=bs-BA"]
    e = ["阿萨姆语=as-IN",
         "奥里亚语=or-IN",
         "巴斯克语=eu-ES",
         "保加利亚语=bg-BG",
         "波兰语=pl-PL",
         "波斯语=fa-IR",
         "丹麦语=da-DK",
         "德语=de-DE",
         "德语(瑞士)=de-CH",
         "芬兰语=fi-FI",
         "古吉拉特语=gu-IN",
         "哈萨克语=kk-KZ",
         "荷兰语=nl-NL",
         "加利西亚语=gl-ES",
         "加泰罗尼亚语=ca-ES",
         "捷克语=cs-CZ",
         "卡纳达语=kn-IN",
         "克罗地亚语=hr-HR",
         "罗马尼亚语=ro-RO",
         "马拉地语=mr-IN",
         "马拉雅拉姆语=ml-IN",
         "挪威语=nb-NO",
         "旁遮普语=pa-IN",
         "葡萄牙语(巴西)=pt-BR",
         "葡萄牙语(葡萄牙)=pt-PT",
         "瑞典语=sv-SE",
         "塞尔维亚语=sr-RS",
         "僧伽罗语=si-LK",
         "斯洛伐克语=sk-SK",
         "斯洛文尼亚语=sl-SI",
         "斯瓦西里语=sw-KE",
         "泰卢固语=te-IN",
         "泰米尔语=ta-IN",
         "土耳其语=tr-TR",
         "乌尔都语（巴基斯坦）=ur-PK",
         "乌克兰语=uk-UA",
         "乌兹别克语=uz-UZ",
         "西班牙语(墨西哥)=es-MX",
         "西班牙语(西班牙)=es-ES",
         "希伯来语（以色列）=iw-IL",
         "希腊语=el-GR",
         "匈牙利语=hu-HU",
         "意大利语=it-IT",
         "英文（澳大利亚）=en-AU",
         "英文（新西兰）=en-NZ",
         "英语（英国）=en-GB",
         "中文（中国）=zh-CN",
         "数字语言=kea-CV",
         "英语（美国）=en-US",
         "阿塞拜疆语（阿塞拜疆）=az-AZ",
         "格鲁吉亚语（格鲁吉亚）=ka-GE",
         "亚美尼亚语（亚美尼亚）=hy-AM",
         "波斯尼亚语=bs-BA"]
    d_rtl = ["阿拉伯语（阿拉伯）=ar-AR", "维吾尔语（中国）=ug-CN"]
    d_ltr = ["藏语（中国）=bo-CN",
             "俄语=ru-RU",
             "法语=fr-FR",
             "菲律宾语=fil-PH",
             "高棉语=km-KH",
             "韩语=ko-KR",
             "老挝语=lo-LA",
             "马来语=ms-MY",
             "孟加拉语=bn-BD",
             "缅甸语(MM)=My-MM",
             "尼泊尔语=ne-NP",
             "日语=ja-JP",
             "泰语=th-TH",
             "印地语=hi-IN",
             "印尼语=id-ID",
             "英语（美国）=en-US",
             "越南语=vi-VN",
             "中文（台湾）=zh-TW",
             "中文（香港）=zh-HK",
             "中文（中国）=zh-CN",
             "数字语言=kea-CV", ]
    e_rtl = ["阿拉伯语（阿拉伯）=ar-AR", "波斯语=fa-IR", "乌尔都语（巴基斯坦）=ur-PK", "希伯来语（以色列）=iw-IL"]
    e_ltr = ["阿萨姆语=as-IN",
             "奥里亚语=or-IN",
             "巴斯克语=eu-ES",
             "保加利亚语=bg-BG",
             "波兰语=pl-PL",
             "丹麦语=da-DK",
             "德语=de-DE",
             "德语(瑞士)=de-CH",
             "芬兰语=fi-FI",
             "古吉拉特语=gu-IN",
             "哈萨克语=kk-KZ",
             "荷兰语=nl-NL",
             "加利西亚语=gl-ES",
             "加泰罗尼亚语=ca-ES",
             "捷克语=cs-CZ",
             "卡纳达语=kn-IN",
             "克罗地亚语=hr-HR",
             "罗马尼亚语=ro-RO",
             "马拉地语=mr-IN",
             "马拉雅拉姆语=ml-IN",
             "挪威语=nb-NO",
             "旁遮普语=pa-IN",
             "葡萄牙语(巴西)=pt-BR",
             "葡萄牙语(葡萄牙)=pt-PT",
             "瑞典语=sv-SE",
             "塞尔维亚语=sr-RS",
             "僧伽罗语=si-LK",
             "斯洛伐克语=sk-SK",
             "斯洛文尼亚语=sl-SI",
             "斯瓦西里语=sw-KE",
             "泰卢固语=te-IN",
             "泰米尔语=ta-IN",
             "土耳其语=tr-TR",
             "乌克兰语=uk-UA",
             "乌兹别克语=uz-UZ",
             "西班牙语(墨西哥)=es-MX",
             "西班牙语(西班牙)=es-ES",
             "希腊语=el-GR",
             "匈牙利语=hu-HU",
             "意大利语=it-IT",
             "英文（澳大利亚）=en-AU",
             "英文（新西兰）=en-NZ",
             "英语（英国）=en-GB",
             "阿塞拜疆语（阿塞拜疆）=az-AZ",
             "格鲁吉亚语（格鲁吉亚）=ka-GE",
             "亚美尼亚语（亚美尼亚）=hy-AM",
             "波斯尼亚语=bs-BA"]
    de_rtl = ["阿拉伯语（阿拉伯）=ar-AR",
              "波斯语=fa-IR",
              "维吾尔语（中国）=ug-CN",
              "乌尔都语（巴基斯坦）=ur-PK",
              "希伯来语（以色列）=iw-IL", ]
    de_ltr = ["阿萨姆语=as-IN",
              "奥里亚语=or-IN",
              "巴斯克语=eu-ES",
              "保加利亚语=bg-BG",
              "波兰语=pl-PL",
              "藏语（中国）=bo-CN",
              "丹麦语=da-DK",
              "德语=de-DE",
              "德语(瑞士)=de-CH",
              "俄语=ru-RU",
              "法语=fr-FR",
              "菲律宾语=fil-PH",
              "芬兰语=fi-FI",
              "高棉语=km-KH",
              "古吉拉特语=gu-IN",
              "哈萨克语=kk-KZ",
              "韩语=ko-KR",
              "荷兰语=nl-NL",
              "加利西亚语=gl-ES",
              "加泰罗尼亚语=ca-ES",
              "捷克语=cs-CZ",
              "卡纳达语=kn-IN",
              "克罗地亚语=hr-HR",
              "老挝语=lo-LA",
              "罗马尼亚语=ro-RO",
              "马拉地语=mr-IN",
              "马拉雅拉姆语=ml-IN",
              "马来语=ms-MY",
              "孟加拉语=bn-BD",
              "缅甸语(MM)=My-MM",
              "尼泊尔语=ne-NP",
              "挪威语=nb-NO",
              "旁遮普语=pa-IN",
              "葡萄牙语(巴西)=pt-BR",
              "葡萄牙语(葡萄牙)=pt-PT",
              "日语=ja-JP",
              "瑞典语=sv-SE",
              "塞尔维亚语=sr-RS",
              "僧伽罗语=si-LK",
              "斯洛伐克语=sk-SK",
              "斯洛文尼亚语=sl-SI",
              "斯瓦西里语=sw-KE",
              "泰卢固语=te-IN",
              "泰米尔语=ta-IN",
              "泰语=th-TH",
              "土耳其语=tr-TR",
              "乌克兰语=uk-UA",
              "乌兹别克语=uz-UZ",
              "西班牙语(墨西哥)=es-MX",
              "西班牙语(西班牙)=es-ES",
              "希腊语=el-GR",
              "匈牙利语=hu-HU",
              "意大利语=it-IT",
              "印地语=hi-IN",
              "印尼语=id-ID",
              "英文（澳大利亚）=en-AU",
              "英文（新西兰）=en-NZ",
              "英语（美国）=en-US",
              "英语（英国）=en-GB",
              "越南语=vi-VN",
              "中文（台湾）=zh-TW",
              "中文（香港）=zh-HK",
              "中文（中国）=zh-CN",
              "数字语言=kea-CV",
              "阿塞拜疆语（阿塞拜疆）=az-AZ",
              "格鲁吉亚语（格鲁吉亚）=ka-GE",
              "亚美尼亚语（亚美尼亚）=hy-AM",
              "波斯尼亚语=bs-BA"]

    def __init__(self):
        pass

    def get_language(self, lang):
        if lang == "内销":
            return self.d
        elif lang == "外销":
            return self.e
        elif lang == "内外销":
            return self.de
        elif lang == "内销RTL":
            return self.d_rtl
        elif lang == "外销RTL":
            return self.e_rtl
        elif lang == "内销LTR":
            return self.d_ltr
        elif lang == "外销LTR":
            return self.e_ltr
        elif lang == "内外销LTR":
            return self.de_ltr
        elif lang == "内外销RTL":
            return self.de_rtl
        else:
            return None
